###############################################################################
#File Name: storage_tasks_01.yml                                              #
###############################################################################

    #Get API versions available
    - name: Retrieve and store API versions from api_version endpoint
      uri:
        url: https://application.client.com/api/api_version
        method: GET 
        validate_certs: no
        return_content: yes
        ignore_errors: yes
      register: api_version
    
    #Target specific API version to use for token retrieval
    - name: Retrieve API token for later use 
      uri:
        url: https://application.client.com/api/{{ api_version.json.version | last }}/auth/apitoken
        method: POST
        validate_certs: no
        return_content: yes
        ignore_errors: true
        body:
          username: "user01"
          password: "P@ssw0rd1!"
        body_format: json
        register: api_token_data
        
    #Use token for some storage related task if successful API token retrieval 
    - name: Perform storage related tasks authenticating via API token
      uri:
        url: https://application.client.com/api.{{ api_version.json.version | last }}/provision_storage
        method: POST
        validate_cers: no
        return_content: yes
        ignore_errors: yes
        body:
          api_token: "{{ api_token_data.json.api_token }}"
        body_format: json
        register: provision_session
        when: (api_token_data.status == 200)
        
    #Additional tasks as needed