---
# example Infrastructure inventory
all:
  children:
    # group definition
    group01:    
        hosts:
          # FQDNs or IPs
          group01.vlab.local:
    group02:
        hosts:
#          10.0.0.2:
          10.0.0.3:
            # host-specific variables
            Switch01: true
            Switch02: "on"
            Switch03: 42
    group03:
        hosts:
#          10.0.0.4:
          10.0.0.5:
            file_check:
              file_check01: true
              file_check02: false
            test_switch: 01
