################################################################################
##File Name: parent_playbook_01.yml                                            #
################################################################################
---

################################################################################
##Storage Provisioning Tasks                                                   #
################################################################################
- name: Storage provisioning
  hosts: group01
  gather_facts: false
  tasks:
    ###########################################################################
    #Ansible roles to perform reusable provisioning tasks                     #
    ###########################################################################
    - name: Storage related processing 01
      include_role:
        name: storage_task01
